# 430_dataset_for_Kaggle
## Purpose 
In this notebook we prepare a dataframe to publish to Kaggle.  
## Datasets 
* _Input_: Joined1617.csv,Joined1516.csv,Joined1415.csv,Joined1314.csv,Joined1213.csv
* _Output_: kaggle.csv

In [1]:
import math
import os.path
import numpy as np
import pandas as pd

### Reading in our cleaned Joined datasets from 16-17 to 12-13.

In [2]:
DF1 = pd.read_csv("../../data/prep/Joined1617.csv")
DF2 = pd.read_csv("../../data/prep/Joined1516.csv")
DF3 = pd.read_csv("../../data/prep/Joined1415.csv")
DF4 = pd.read_csv("../../data/prep/Joined1314.csv")
DF5 = pd.read_csv("../../data/prep/Joined1213.csv")

#### Selecting all FIFA columns in index

In [3]:
index = ['Players','club','league','age','nationality','Position','overall','pac','sho',
 'pas', 'dri', 'def', 'phy', 'international_reputation', 'skill_moves',
 'weak_foot', 'work_rate_att', 'work_rate_def', 'preferred_foot', 'crossing',
 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling',
 'curve', 'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration',
 'sprint_speed', 'agility', 'reactions', 'balance','shot_power','jumping',
 'stamina','strength','long_shots','aggression','interceptions','positioning', 'vision',
 'penalties', 'composure', 'marking', 'standing_tackle', 'sliding_tackle',
 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']

### Concatting each years index and selecting all columns with data for every year in Fantasy dataset

In [4]:
s1 = DF1.drop_duplicates(index).set_index(index)[['Points','Start', 'Sub','Goals','A','CS','CS part','Yellow','Red','Sub','CO','Off','Pen SV','Pen M','Goals conceded','Conceded 1+','OG','Apps','Form']]
s2 = DF2.drop_duplicates(index).set_index(index)[['Points','Start', 'Sub','Goals','A','CS','CS part','Yellow','Red','Sub','CO','Off','Pen SV','Pen M','Goals conceded','Conceded 1+','OG','Apps','Form']]
s3 = DF3.drop_duplicates(index).set_index(index)[['Points','Start', 'Sub','Goals','A','CS','CS part','Yellow','Red','Sub','CO','Off','Pen SV','Pen M','Goals conceded','Conceded 1+','OG','Apps','Form']]
s4 = DF4.drop_duplicates(index).set_index(index)[['Points','Start', 'Sub','Goals','A','CS','CS part','Yellow','Red','Sub','CO','Off','Pen SV','Pen M','Goals conceded','Conceded 1+','OG','Apps','Form']]
s5 = DF5.drop_duplicates(index).set_index(index)[['Points','Start', 'Sub','Goals','A','CS','CS part','Yellow','Red','Sub','CO','Off','Pen SV','Pen M','Goals conceded','Conceded 1+','OG','Apps','Form']]

kaggle = pd.concat([s1,s2,s3,s4,s5], axis=1, keys=('16/17','15/16','14/15','13/14','12/13')).fillna(0).astype(float).reset_index()

#### Quick look at finished dataframe

In [5]:
kaggle.head(10)

             Players                 club                    league age  \

0    Aaron Cresswell      West Ham United    English Premier League  27
1       Aaron Hughes  Heart of Midlothian      Scottish Premiership  37
2         Aaron Hunt         Hamburger SV         German Bundesliga  30
3       Aaron Lennon              Everton    English Premier League  30
4   Aaron Leya Iseka     SV Zulte-Waregem  Belgian First Division A  19
5       Aaron Niguez          Real Oviedo  Spanish Segunda Division  28
6     Aaron Ramsdale          Bournemouth    English Premier League  19
7       Aaron Ramsey              Arsenal    English Premier League  26
8       Aaron Seydel        Holstein Kiel      German 2. Bundesliga  21
9  Aaron Wan-Bissaka       Crystal Palace    English Premier League  19

        nationality    Position overall pac sho pas    ...    12/13        \
                                                       ...      Sub    CO
0           England    Defender      76  76  59  72    ...      0.0   0.0
1  Northern Ireland    Defender      71  23  35  52    ...     15.0   1.0
2           Germany  Midfielder      76  68  73  75    ...      2.0   2.0
3           England  Midfielder      77  83  64  71    ...      1.0   1.0
4           Belgium     Forward      68  79  69  49    ...      0.0   0.0
5             Spain  Midfielder      73  82  65  68    ...      0.0   0.0
6           England  Goalkeeper      61  62  59  53    ...      0.0   0.0
7             Wales  Midfielder      82  68  75  79    ...     17.0  15.0
8           Germany     Forward      64  61  62  44    ...      0.0   0.0
9          DR Congo     Forward      55  73  48  50    ...      0.0   0.0


    Off Pen SV Pen M Goals conceded Conceded 1+   OG  Apps      Form
0   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000
1   0.0    0.0   0.0           43.0        23.0  0.0  24.0  1.625000
2   6.0    0.0   1.0            0.0         0.0  0.0  28.0  4.035714
3  15.0    0.0   0.0            0.0         0.0  0.0  34.0  3.147059
4   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000
5   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000
6   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000
7   5.0    0.0   0.0            0.0         0.0  0.0  36.0  1.833333
8   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000
9   0.0    0.0   0.0            0.0         0.0  0.0   0.0  0.000000

[10 rows x 148 columns]

#### Saving to csv file in data/final to be publish to kaggle

In [6]:
kaggle.to_csv('../../data/final/FIFAvsReal-Life.csv')