In [1]:
import os.path
import numpy as np
import pandas as pd

In [2]:
Fifa = pd.read_csv("FIFADS.csv")

# 1617

In [3]:
Fantasy1617 = pd.read_csv("FANTASY1617DS.csv")

In [4]:
Join1617 = pd.merge(Fifa, Fantasy1617, on=['Surname','FirstInitial'])

In [5]:
Join1617.drop(Join1617.columns[[0]], axis=1, inplace=True)

In [6]:
i = 0
array = []

while i <= 1982:
    if Join1617['Firstname'][i] in Join1617['name'][i] or Join1617['Firstname'][i] in Join1617['full_name'][i]:
        array.append(True)
        i+=1
    else:
        array.append(False)
        i+=1

In [7]:
array = np.array(array)

In [8]:
Join1617 = Join1617[array]

In [9]:
Error1617 = Join1617[(Join1617['Players'].isin(Join1617['Players'][Join1617['Players'].duplicated()]) | Join1617['full_name'].isin(Join1617['full_name'][Join1617['full_name'].duplicated()]))]

In [10]:
leagues = ['German Bundesliga','Spanish Primera Division','English Premier League']
TopLeagues1617 = Error1617[(Error1617.league.str.contains('|'.join(leagues)) == True) | Error1617['league'].isnull()]

In [11]:
TopLeagues1617[TopLeagues1617['Clubs'].isnull()]

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
312,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,0,8,2,1,0,0,18,7,0,Juanfran
314,188135,Juanfran,Juan Francisco Moreno Fuertes,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,2061,28,Spanish Primera Division,1988-09-11,180.0,...,0,8,2,1,0,0,18,7,0,Juanfran
910,208141,Gabriel,Gabriel Appelt Pires,CD Leganes,https://cdn.sofifa.org/18/teams/100888.png,2013,23,Spanish Primera Division,1993-09-18,187.0,...,0,1,1,13,0,0,0,0,0,Gabriel
1305,221452,Nano,Alexander Mesa Travieso,Levante UD,https://cdn.sofifa.org/18/teams/1853.png,1768,22,Spanish Primera Division,1995-02-05,178.0,...,0,13,5,1,0,0,0,0,0,Nano
1335,232805,Bernardo,Bernardo Fernandes,RB Leipzig,https://cdn.sofifa.org/18/teams/112172.png,1793,22,German Bundesliga,1995-05-14,186.0,...,0,6,1,3,0,0,0,0,0,Bernardo
1394,145889,Tito,Roberto Roman Triguero,CD Leganes,https://cdn.sofifa.org/18/teams/100888.png,1814,31,Spanish Primera Division,1985-07-11,175.0,...,0,4,2,4,0,0,41,24,0,Tito
1805,235365,Juan Moreno,Juan Moreno Fernandez,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,1543,20,Spanish Primera Division,1997-05-11,175.0,...,0,5,0,0,0,0,0,0,0,Juan

In [12]:
Fix1617 = TopLeagues1617[(TopLeagues1617['Players'].isin(TopLeagues1617['Players'][TopLeagues1617['Players'].duplicated()]) | TopLeagues1617['full_name'].isin(TopLeagues1617['full_name'][TopLeagues1617['full_name'].duplicated()]))]

In [13]:
Fix1617 = Fix1617.drop(Fix1617.index[[2,4,5,6,7,11,13,15,16,18,25,26,31,32]])

In [14]:
d = {
 'ID' : 'first',
 'club_logo':'first',
 'special':'first',
 'age':'first',
 'league':'first',
 'birth_date':'first',
 'height_cm':'first',
 'weight_kg':'first',
 'body_type':'first',
 'real_face':'first',
 'flag':'first',
 'nationality':'first',
 'photo':'first',
 'eur_value':'first',
 'eur_wage':'first',
 'eur_release_clause':'first',
 'overall':'first',
 'potential':'first',
 'pac':'first',
 'sho':'first',
 'pas':'first',
 'dri':'first',
 'def':'first',
 'phy':'first',
 'international_reputation':'first',
 'skill_moves':'first',
 'weak_foot':'first',
 'work_rate_att':'first',
 'work_rate_def':'first',
 'preferred_foot':'first',
 'crossing':'first',
 'finishing':'first',
 'heading_accuracy':'first',
 'short_passing':'first',
 'volleys':'first',
 'dribbling':'first',
 'curve':'first',
 'free_kick_accuracy':'first',
 'long_passing':'first',
 'ball_control':'first',
 'acceleration':'first',
 'sprint_speed':'first',
 'agility':'first',
 'reactions':'first',
 'balance':'first',
 'shot_power':'first',
 'jumping':'first',
 'stamina':'first',
 'strength':'first',
 'long_shots':'first',
 'aggression':'first',
 'interceptions':'first',
 'positioning':'first',
 'vision':'first',
 'penalties':'first',
 'composure':'first',
 'marking':'first',
 'standing_tackle':'first',
 'sliding_tackle':'first',
 'gk_diving':'first',
 'gk_handling':'first',
 'gk_kicking':'first',
 'gk_positioning':'first',
 'gk_reflexes':'first',
 'rs':'first',
 'rw':'first',
 'rf':'first',
 'ram':'first',
 'rcm':'first',
 'rm':'first',
 'rdm':'first',
 'rcb':'first',
 'rb':'first',
 'rwb':'first',
 'st':'first',
 'lw':'first',
 'cf':'first',
 'cam':'first',
 'cm':'first',
 'lm':'first',
 'cdm':'first',
 'cb':'first',
 'lb':'first',
 'lwb':'first',
 'ls':'first',
 'lf':'first',
 'lam':'first',
 'lcm':'first',
 'ldm':'first',
 'lcb':'first',
 'gk':'first',
 '1_on_1_rush_trait':'first',
 'acrobatic_clearance_trait':'first',
 'argues_with_officials_trait':'first',
 'avoids_using_weaker_foot_trait':'first',
 'backs_into_player_trait':'first',
 'bicycle_kicks_trait':'first',
 'cautious_with_crosses_trait':'first',
 'chip_shot_trait':'first',
 'chipped_penalty_trait':'first',
 'comes_for_crosses_trait':'first',
 'corner_specialist_trait':'first',
 'diver_trait':'first',
 'dives_into_tackles_trait':'first',
 'diving_header_trait':'first',
 'driven_pass_trait':'first',
 'early_crosser_trait':'first',
 "fan's_favourite_trait":'first',
 'fancy_flicks_trait':'first',
 'finesse_shot_trait':'first',
 'flair_trait':'first',
 'flair_passes_trait':'first',
 'gk_flat_kick_trait':'first',
 'gk_long_throw_trait':'first',
 'gk_up_for_corners_trait':'first',
 'giant_throw_in_trait':'first',
 'inflexible_trait':'first',
 'injury_free_trait':'first',
 'injury_prone_trait':'first',
 'leadership_trait':'first',
 'long_passer_trait':'first',
 'long_shot_taker_trait':'first',
 'long_throw_in_trait':'first',
 'one_club_player_trait':'first',
 'outside_foot_shot_trait':'first',
 'playmaker_trait':'first',
 'power_free_kick_trait':'first',
 'power_header_trait':'first',
 'puncher_trait':'first',
 'rushes_out_of_goal_trait':'first',
 'saves_with_feet_trait':'first',
 'second_wind_trait':'first',
 'selfish_trait':'first',
 'skilled_dribbling_trait':'first',
 'stutter_penalty_trait':'first',
 'swerve_pass_trait':'first',
 'takes_finesse_free_kicks_trait':'first',
 'target_forward_trait':'first',
 'team_player_trait':'first',
 'technical_dribbler_trait':'first',
 'tries_to_beat_defensive_line_trait':'first',
 'poacher_speciality':'first',
 'speedster_speciality':'first',
 'aerial_threat_speciality':'first',
 'dribbler_speciality':'first',
 'playmaker_speciality':'first',
 'engine_speciality':'first',
 'distance_shooter_speciality':'first',
 'crosser_speciality':'first',
 'free_kick_specialist_speciality':'first',
 'tackling_speciality':'first',
 'tactician_speciality':'first',
 'acrobat_speciality':'first',
 'strength_speciality':'first',
 'clinical_finisher_speciality':'first',
 'prefers_rs':'first',
 'prefers_rw':'first',
 'prefers_rf':'first',
 'prefers_ram':'first',
 'prefers_rcm':'first',
 'prefers_rm':'first',
 'prefers_rdm':'first',
 'prefers_rcb':'first',
 'prefers_rb':'first',
 'prefers_rwb':'first',
 'prefers_st':'first',
 'prefers_lw':'first',
 'prefers_cf':'first',
 'prefers_cam':'first',
 'prefers_cm':'first',
 'prefers_lm':'first',
 'prefers_cdm':'first',
 'prefers_cb':'first',
 'prefers_lb':'first',
 'prefers_lwb':'first',
 'prefers_ls':'first',
 'prefers_lf':'first',
 'prefers_lam':'first',
 'prefers_lcm':'first',
 'prefers_ldm':'first',
 'prefers_lcb':'first',
 'prefers_gk':'first',
 'Players':'first',
 'Position':'first',
 'Clubs':'first',
 'Points':'sum',  
 'Start':'sum', 
 'Sub':'sum', 
 'club':'last',
 'Position':'first',
 'Start':'sum',
 'Goals':'sum',
 'A':'sum',
 'CS':'sum',
 'CS part':'sum',
 'Yellow':'sum',
 'Red':'sum',
 'Sub':'sum',
 'CO':'sum',
 'Off':'sum',
 'Pen SV':'sum',
 'Pen M':'sum',
 'Goals conceded':'sum',
 'Conceded 1+':'sum',
 'OG':'sum',
 'Firstname':'first'}

In [15]:
Fixed1617 = (Fix1617.groupby(['name','full_name'], sort=False, as_index=False).agg(d).reindex(columns=Fix1617.columns))

In [16]:
Fixed1617.head(5)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,192227,S. Mustafi,Shkodran Mustafi,Arsenal,https://cdn.sofifa.org/18/teams/1.png,1942,25,English Premier League,1992-04-17,184.0,...,0,2,1,1,0,0,35,16,0,Shkodran
1,200228,Bruno,Bruno Gonzalez Cabrera,Getafe CF,https://cdn.sofifa.org/18/teams/1860.png,1533,27,Spanish Primera Division,1990-05-24,185.0,...,0,16,1,1,0,0,19,10,0,Bruno
2,174543,C. Bravo,Claudio Bravo,Manchester City,https://cdn.sofifa.org/18/teams/10.png,1464,34,English Premier League,1983-04-13,184.0,...,0,8,0,1,1,0,28,11,0,Claudio
3,171919,Naldo,Ronaldo Aparecido Rodrigues,FC Schalke 04,https://cdn.sofifa.org/18/teams/34.png,1949,34,German Bundesliga,1982-09-10,198.0,...,1,1,0,0,0,0,18,5,0,Naldo
4,167431,G. Castro,Gonzalo Castro,Borussia Dortmund,https://cdn.sofifa.org/18/teams/22.png,2156,30,German Bundesliga,1987-06-11,172.0,...,0,6,5,10,0,0,0,0,0,Gonzalo

In [17]:
Delete1617 = Error1617[Error1617.league.str.contains('|'.join(leagues)) == False]

In [18]:
Join1617 = Join1617[(~(Join1617.full_name.isin(Delete1617.full_name) & Join1617.birth_date.isin(Delete1617.birth_date)))]
Join1617 = Join1617[(~(Join1617.full_name.isin(Fix1617.full_name) & Join1617.birth_date.isin(Fix1617.birth_date)))]

In [19]:
Joined1617 = pd.concat([Join1617,Fixed1617])
Joined1617 = Joined1617.reset_index()

In [20]:
Joined1617.drop(Joined1617.columns[[0]], axis=1, inplace=True)

# 1516

In [21]:
Fantasy1516 = pd.read_csv("FANTASY1516DS.csv")

In [22]:
Join1516 = pd.merge(Fifa, Fantasy1516, on=['Surname','FirstInitial'])

In [23]:
Join1516.drop(Join1516.columns[[0]], axis=1, inplace=True)

In [24]:
i = 0
array = []

while i <= 1895:
    if Join1516['Firstname'][i] in Join1516['name'][i] or Join1516['Firstname'][i] in Join1516['full_name'][i]:
        array.append(True)
        i+=1
    else:
        array.append(False)
        i+=1

In [25]:
array = np.array(array)

In [26]:
Join1516 = Join1516[array]

In [27]:
Error1516 = Join1516[(Join1516['Players'].isin(Join1516['Players'][Join1516['Players'].duplicated()]) | Join1516['full_name'].isin(Join1516['full_name'][Join1516['full_name'].duplicated()]))]

In [28]:
TopLeagues1516 = Error1516[(Error1516.league.str.contains('|'.join(leagues)) == True) | Error1516['league'].isnull()]

In [29]:
TopLeagues1516[TopLeagues1516['Clubs'].isnull()].head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
224,208421,Saul,Saul Niguez Esclapez,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2092,22,Spanish Primera Division,1994-11-21,181.0,...,0,19,13,12,0,0,0,0,0,Saul
225,219709,Saul,Saul Garcia Cabrero,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,1719,22,Spanish Primera Division,1994-11-09,183.0,...,0,19,13,12,0,0,0,0,0,Saul
312,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,0,2,1,1,0,0,16,4,0,Juanfran

In [30]:
Fix1516 = TopLeagues1516[(TopLeagues1516['Players'].isin(TopLeagues1516['Players'][TopLeagues1516['Players'].duplicated()]) | TopLeagues1516['full_name'].isin(TopLeagues1516['full_name'][TopLeagues1516['full_name'].duplicated()]))]

In [31]:
Fixed1516 = (Fix1516.groupby(['name','full_name'], sort=False, as_index=False).agg(d).reindex(columns=Fix1516.columns))

In [32]:
Delete1516 = Error1516[Error1516.league.str.contains('|'.join(leagues)) == False]

In [33]:
Join1516 = Join1516[(~(Join1516.full_name.isin(Delete1516.full_name) & Join1516.birth_date.isin(Delete1516.birth_date)))]
Join1516 = Join1516[(~(Join1516.full_name.isin(Fix1516.full_name) & Join1516.birth_date.isin(Fix1516.birth_date)))]

In [34]:
Joined1516 = pd.concat([Join1516,Fixed1516])
Joined1516 = Joined1516.reset_index()

In [35]:
Joined1516.drop(Joined1516.columns[[0]], axis=1, inplace=True)

In [36]:
Joined1516.head(5)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2228,32,Spanish Primera Division,1985-02-05,185.0,...,0,0,0,2,0,2,0,0,0,Cristiano
1,158023,L. Messi,Lionel Messi,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2158,30,Spanish Primera Division,1987-06-24,170.0,...,0,2,2,2,0,3,0,0,0,Lionel
2,190871,Neymar,Neymar da Silva Santos Jr.,Paris Saint-Germain,https://cdn.sofifa.org/18/teams/73.png,2100,25,French Ligue 1,1992-02-05,175.0,...,0,0,0,1,0,2,0,0,0,Neymar
3,176580,L. Suarez,Luis Suarez,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2291,30,Spanish Primera Division,1987-01-24,182.0,...,0,2,0,0,0,2,0,0,0,Luis
4,167495,M. Neuer,Manuel Neuer,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,1493,31,German Bundesliga,1986-03-27,193.0,...,0,0,0,1,0,0,17,3,0,Manuel

In [37]:
Fixed1516.head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,192985,K. De Bruyne,Kevin De Bruyne,Manchester City,https://cdn.sofifa.org/18/teams/10.png,2162,26,English Premier League,1991-06-28,181.0,...,0,4,3,5,0,0,0,0,0,Kevin
1,176676,Marcelo,Marcelo Vieira da Silva,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2214,29,Spanish Primera Division,1988-05-12,174.0,...,0,4,2,3,0,0,60,25,0,Marcelo
2,184120,Bruno,Bruno Soriano Llido,Villarreal CF,https://cdn.sofifa.org/18/teams/483.png,2059,33,Spanish Primera Division,1984-06-12,184.0,...,0,2,0,3,0,0,39,19,0,Bruno

# 1415

In [38]:
Fantasy1415 = pd.read_csv("FANTASY1415DS.csv")

In [39]:
Join1415 = pd.merge(Fifa, Fantasy1415, on=['Surname','FirstInitial'])

In [40]:
Join1415.drop(Join1415.columns[[0]], axis=1, inplace=True)

In [41]:
i = 0
array = []

while i <= 1769:
    if Join1415['Firstname'][i] in Join1415['name'][i] or Join1415['Firstname'][i] in Join1415['full_name'][i]:
        array.append(True)
        i+=1
    else:
        array.append(False)
        i+=1

In [42]:
array = np.array(array)

In [43]:
Join1415 = Join1415[array]

In [44]:
Error1415 = Join1415[(Join1415['Players'].isin(Join1415['Players'][Join1415['Players'].duplicated()]) | Join1415['full_name'].isin(Join1415['full_name'][Join1415['full_name'].duplicated()]))]

In [45]:
TopLeagues1415 = Error1415[(Error1415.league.str.contains('|'.join(leagues)) == True) | Error1415['league'].isnull()]

In [46]:
TopLeagues1415[TopLeagues1415['Clubs'].isnull()].head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
186,208421,Saul,Saul Niguez Esclapez,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2092,22,Spanish Primera Division,1994-11-21,181.0,...,0,5,4,17,0,0,0,0,0,Saul
187,219709,Saul,Saul Garcia Cabrero,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,1719,22,Spanish Primera Division,1994-11-09,183.0,...,0,5,4,17,0,0,0,0,0,Saul
250,171919,Naldo,Ronaldo Aparecido Rodrigues,FC Schalke 04,https://cdn.sofifa.org/18/teams/34.png,1949,34,German Bundesliga,1982-09-10,198.0,...,0,7,2,0,0,0,48,20,0,Naldo

In [47]:
Fix1415 = TopLeagues1415[(TopLeagues1415['Players'].isin(TopLeagues1415['Players'][TopLeagues1415['Players'].duplicated()]) | TopLeagues1415['full_name'].isin(TopLeagues1415['full_name'][TopLeagues1415['full_name'].duplicated()]))]

In [48]:
Delete1415 = Error1415[Error1415.league.str.contains('|'.join(leagues)) == False]

In [49]:
Fixed1415 = (Fix1415.groupby(['name','full_name'], sort=False, as_index=False).agg(d).reindex(columns=Fix1415.columns))

In [50]:
Join1415 = Join1415[(~(Join1415.full_name.isin(Delete1415.full_name) & Join1415.birth_date.isin(Delete1415.birth_date)))]
Join1415 = Join1415[(~(Join1415.full_name.isin(Fix1415.full_name) & Join1415.birth_date.isin(Fix1415.birth_date)))]

In [51]:
Joined1415 = pd.concat([Join1415,Fixed1415])
Joined1415 = Joined1415.reset_index()

In [52]:
Joined1415.drop(Joined1415.columns[[0]], axis=1, inplace=True)

In [53]:
Joined1415.head(30)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2228,32,Spanish Primera Division,1985-02-05,185.0,...,1,0,0,3,0,2,0,0,0,Cristiano
1,158023,L. Messi,Lionel Messi,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2158,30,Spanish Primera Division,1987-06-24,170.0,...,0,1,1,0,0,1,0,0,0,Lionel
2,190871,Neymar,Neymar da Silva Santos Jr.,Paris Saint-Germain,https://cdn.sofifa.org/18/teams/73.png,2100,25,French Ligue 1,1992-02-05,175.0,...,0,5,4,9,0,0,0,0,0,Neymar
3,176580,L. Suarez,Luis Suarez,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2291,30,Spanish Primera Division,1987-01-24,182.0,...,0,3,2,11,0,0,0,0,0,Luis
4,167495,M. Neuer,Manuel Neuer,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,1493,31,German Bundesliga,1986-03-27,193.0,...,0,2,1,0,1,0,18,6,0,Manuel
5,188545,R. Lewandowski,Robert Lewandowski,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,2146,28,German Bundesliga,1988-08-21,185.0,...,0,4,3,11,0,0,0,0,0,Robert
6,193080,De Gea,David De Gea Quintana,Manchester United,https://cdn.sofifa.org/18/teams/11.png,1458,26,English Premier League,1990-11-07,193.0,...,0,0,0,1,1,0,37,10,0,David
7,183277,E. Hazard,Eden Hazard,Chelsea,https://cdn.sofifa.org/18/teams/5.png,2096,26,English Premier League,1991-01-07,173.0,...,0,0,0,12,0,1,0,0,0,Eden
8,182521,T. Kroos,Toni Kroos,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2165,27,Spanish Primera Division,1990-01-04,182.0,...,0,1,0,8,0,0,0,0,0,Toni
9,155862,Sergio Ramos,Sergio Ramos Garcia,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2153,31,Spanish Primera Division,1986-03-30,183.0,...,0,0,0,5,0,0,27,10,0,Sergio
10,192985,K. De Bruyne,Kevin De Bruyne,Manchester City,https://cdn.sofifa.org/18/teams/10.png,2162,26,English Premier League,1991-06-28,181.0,...,0,0,0,4,0,0,0,0,0,Kevin
11,192119,T. Courtois,Thibaut Courtois,Chelsea,https://cdn.sofifa.org/18/teams/5.png,1282,25,English Premier League,1992-05-11,199.0,...,0,5,0,1,0,0,30,11,0,Thibaut
12,184941,A. Sanchez,Alexis Sanchez,Arsenal,https://cdn.sofifa.org/18/teams/1.png,2181,28,English Premier League,1988-12-19,169.0,...,0,2,1,12,0,1,0,0,0,Alexis
13,177003,L. Modric,Luka Modric,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2228,31,Spanish Primera Division,1985-09-09,174.0,...,0,1,0,9,0,0,0,0,0,Luka
14,173731,G. Bale,Gareth Bale,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2259,27,Spanish Primera Division,1989-07-16,183.0,...,0,3,1,7,0,0,0,0,0,Gareth
15,153079,S. Aguero,Sergio Aguero,Manchester City,https://cdn.sofifa.org/18/teams/10.png,2074,29,English Premier League,1988-06-02,173.0,...,0,3,3,12,0,1,0,0,0,Sergio
16,200389,J. Oblak,Jan Oblak,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,1290,24,Spanish Primera Division,1993-01-07,189.0,...,0,27,0,0,0,0,6,2,0,Jan
17,194765,A. Griezmann,Antoine Griezmann,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2104,26,Spanish Primera Division,1991-03-21,174.0,...,0,8,8,20,0,0,0,0,0,Antoine
18,188567,P. Aubameyang,Pierre-Emerick Aubameyang,Borussia Dortmund,https://cdn.sofifa.org/18/teams/22.png,2073,28,German Bundesliga,1989-06-18,187.0,...,0,3,2,8,0,0,0,0,0,Pierre
19,183907,J. Boateng,Jerome Boateng,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,1989,28,German Bundesliga,1988-09-03,192.0,...,1,4,2,5,0,0,15,5,0,Jerome
20,182493,D. Godin,Diego Godin,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,1937,31,Spanish Primera Division,1986-02-16,186.0,...,0,1,0,0,0,0,24,8,0,Diego
21,178603,M. Hummels,Mats Hummels,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,2038,28,German Bundesliga,1988-12-16,191.0,...,0,2,1,2,0,0,27,11,0,Mats
22,176635,M. Ozil,Mesut Ozil,Arsenal,https://cdn.sofifa.org/18/teams/1.png,1927,28,English Premier League,1988-10-15,180.0,...,0,2,1,5,0,0,0,0,0,Mesut
23,167948,H. Lloris,Hugo Lloris,Tottenham Hotspur,https://cdn.sofifa.org/18/teams/18.png,1318,30,English Premier League,1986-12-26,188.0,...,0,0,0,1,1,0,51,24,0,Hugo
24,9014,A. Robben,Arjen Robben,FC Bayern Munich,https://cdn.sofifa.org/18/teams/21.png,2081,33,German Bundesliga,1984-01-23,180.0,...,0,1,1,6,0,0,0,0,0,Arjen
25,190460,C. Eriksen,Christian Eriksen,Tottenham Hotspur,https://cdn.sofifa.org/18/teams/18.png,2064,25,English Premier League,1992-02-14,182.0,...,0,1,1,11,0,0,0,0,0,Christian
26,202493,Aleix Vidal,Aleix Vidal Parreu,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2037,27,Spanish Primera Division,1989-08-21,177.0,...,0,12,9,3,0,0,0,0,0,Aleix
27,168651,I. Rakitic,Ivan Rakitic,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2129,29,Spanish Primera Division,1988-03-10,184.0,...,0,11,9,11,0,0,0,0,0,Ivan
28,168542,David Silva,David Josue Jimenez Silva,Manchester City,https://cdn.sofifa.org/18/teams/10.png,1977,31,English Premier League,1986-01-08,173.0,...,0,0,0,15,0,0,0,0,0,David
29,202126,H. Kane,Harry Kane,Tottenham Hotspur,https://cdn.sofifa.org/18/teams/18.png,2062,23,English Premier League,1993-07-28,188.0,...,0,8,6,6,0,1,0,0,1,Harry

In [54]:
Fixed1415.head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,176676,Marcelo,Marcelo Vieira da Silva,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2214,29,Spanish Primera Division,1988-05-12,174.0,...,0,5,1,6,0,0,86,39,1,Marcelo
1,189358,S. Kagawa,Shinji Kagawa,Borussia Dortmund,https://cdn.sofifa.org/18/teams/22.png,1874,28,German Bundesliga,1989-03-17,175.0,...,0,11,5,16,0,0,0,0,0,Shinji
2,188152,Oscar,Oscar dos Santos Emboaba,NaN,NaN,1961,25,NaN,1991-09-09,179.0,...,0,5,2,20,0,0,0,0,0,Oscar

# 1314

In [55]:
Fantasy1314 = pd.read_csv("FANTASY1314DS.csv")

In [56]:
Join1314 = pd.merge(Fifa, Fantasy1314, on=['Surname','FirstInitial'])

In [57]:
Join1314.drop(Join1314.columns[[0]], axis=1, inplace=True)

In [58]:
i = 0
array = []

while i <= 1641:
    if Join1314['Firstname'][i] in Join1314['name'][i] or Join1314['Firstname'][i] in Join1314['full_name'][i]:
        array.append(True)
        i+=1
    else:
        array.append(False)
        i+=1

In [59]:
array = np.array(array)

In [60]:
Join1314 = Join1314[array]

In [61]:
Error1314 = Join1314[(Join1314['Players'].isin(Join1314['Players'][Join1314['Players'].duplicated()]) | Join1314['full_name'].isin(Join1314['full_name'][Join1314['full_name'].duplicated()]))]

In [62]:
TopLeagues1314 = Error1314[(Error1314.league.str.contains('|'.join(leagues)) == True) | Error1314['league'].isnull()]

In [63]:
TopLeagues1314[TopLeagues1314['Clubs'].isnull()].head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
251,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,2,1,0,0,0,0,22,6,1,Juanfran
252,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,0,0,0,1,0,0,40,20,0,Juanfran
254,188135,Juanfran,Juan Francisco Moreno Fuertes,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,2061,28,Spanish Primera Division,1988-09-11,180.0,...,2,1,0,0,0,0,22,6,1,Juanfran

In [64]:
Fix1314 = TopLeagues1314[(TopLeagues1314['Players'].isin(TopLeagues1314['Players'][TopLeagues1314['Players'].duplicated()]) | TopLeagues1314['full_name'].isin(TopLeagues1314['full_name'][TopLeagues1314['full_name'].duplicated()]))]

In [65]:
Delete1314 = Error1314[Error1314.league.str.contains('|'.join(leagues)) == False]

In [66]:
Fixed1314 = (Fix1314.groupby(['name','full_name'], sort=False, as_index=False).agg(d).reindex(columns=Fix1314.columns))

In [67]:
Join1314 = Join1314[(~(Join1314.full_name.isin(Delete1314.full_name) & Join1314.birth_date.isin(Delete1314.birth_date)))]
Join1314 = Join1314[(~(Join1314.full_name.isin(Fix1314.full_name) & Join1314.birth_date.isin(Fix1314.birth_date)))]

In [68]:
Joined1314 = pd.concat([Join1314,Fixed1314])
Joined1314 = Joined1314.reset_index()

In [69]:
Joined1314.drop(Joined1314.columns[[0]], axis=1, inplace=True)

In [70]:
Joined1314.head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2228,32,Spanish Primera Division,1985-02-05,185.0,...,1,0,0,3,0,0,0,0,0,Cristiano
1,158023,L. Messi,Lionel Messi,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2158,30,Spanish Primera Division,1987-06-24,170.0,...,0,2,2,4,0,1,0,0,0,Lionel
2,190871,Neymar,Neymar da Silva Santos Jr.,Paris Saint-Germain,https://cdn.sofifa.org/18/teams/73.png,2100,25,French Ligue 1,1992-02-05,175.0,...,0,10,7,11,0,0,0,0,0,Neymar

In [71]:
Fixed1314.head(5)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,192985,K. De Bruyne,Kevin De Bruyne,Manchester City,https://cdn.sofifa.org/18/teams/10.png,2162,26,English Premier League,1991-06-28,181.0,...,0,7,1,8,0,0,0,0,0,Kevin
1,176635,M. Ozil,Mesut Ozil,Arsenal,https://cdn.sofifa.org/18/teams/1.png,1927,28,English Premier League,1988-10-15,180.0,...,0,2,1,13,0,0,0,0,0,Mesut
2,176676,Marcelo,Marcelo Vieira da Silva,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2214,29,Spanish Primera Division,1988-05-12,174.0,...,1,10,4,4,0,0,76,37,0,Marcelo
3,188152,Oscar,Oscar dos Santos Emboaba,NaN,NaN,1961,25,NaN,1991-09-09,179.0,...,0,17,14,20,0,0,0,0,0,Oscar
4,239335,Oscar,Oscar Rodriguez Arnaiz,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,1667,19,Spanish Primera Division,1998-06-28,174.0,...,0,17,14,20,0,0,0,0,0,Oscar

# 1213

In [72]:
Fantasy1213 = pd.read_csv("FANTASY1213DS.csv")

In [73]:
Join1213 = pd.merge(Fifa, Fantasy1213, on=['Surname','FirstInitial'])

In [74]:
Join1213.drop(Join1213.columns[[0]], axis=1, inplace=True)

In [75]:
i = 0
array = []

while i <= 1550:
    if Join1213['Firstname'][i] in Join1213['name'][i] or Join1213['Firstname'][i] in Join1213['full_name'][i]:
        array.append(True)
        i+=1
    else:
        array.append(False)
        i+=1

In [76]:
array = np.array(array)

In [77]:
Join1213 = Join1213[array]

In [78]:
Error1213 = Join1213[(Join1213['Players'].isin(Join1213['Players'][Join1213['Players'].duplicated()]) | Join1213['full_name'].isin(Join1213['full_name'][Join1213['full_name'].duplicated()]))]

In [79]:
TopLeagues1213 = Error1213[(Error1213.league.str.contains('|'.join(leagues)) == True) | Error1213['league'].isnull()]

In [80]:
TopLeagues1213[TopLeagues1213['Clubs'].isnull()].head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
233,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,0,0,0,0,0,0,29,13,2,Juanfran
234,146760,Juanfran,Juan Francisco Torres Belen,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2070,32,Spanish Primera Division,1985-01-09,180.0,...,0,2,1,2,0,0,47,25,0,Juanfran
235,188135,Juanfran,Juan Francisco Moreno Fuertes,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,2061,28,Spanish Primera Division,1988-09-11,180.0,...,0,0,0,0,0,0,29,13,2,Juanfran

In [81]:
Fix1213 = TopLeagues1213[(TopLeagues1213['Players'].isin(TopLeagues1213['Players'][TopLeagues1213['Players'].duplicated()]) | TopLeagues1213['full_name'].isin(TopLeagues1213['full_name'][TopLeagues1213['full_name'].duplicated()]))]

In [82]:
Delete1213 = Error1213[Error1213.league.str.contains('|'.join(leagues)) == False]

In [83]:
Fixed1213 = (Fix1213.groupby(['name','full_name'], sort=False, as_index=False).agg(d).reindex(columns=Fix1213.columns))

In [84]:
Join1213 = Join1213[(~(Join1213.full_name.isin(Delete1213.full_name) & Join1213.birth_date.isin(Delete1213.birth_date)))]
Join1213 = Join1213[(~(Join1213.full_name.isin(Fix1213.full_name) & Join1213.birth_date.isin(Fix1213.birth_date)))]

In [85]:
Joined1213 = pd.concat([Join1213,Fixed1213])
Joined1213 = Joined1213.reset_index()

In [86]:
Joined1213.drop(Joined1213.columns[[0]], axis=1, inplace=True)

In [87]:
Joined1213.head(3)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,2228,32,Spanish Primera Division,1985-02-05,185.0,...,0,4,4,5,0,1,0,0,1,Cristiano
1,158023,L. Messi,Lionel Messi,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2158,30,Spanish Primera Division,1987-06-24,170.0,...,0,4,4,0,0,0,0,0,0,Lionel
2,176580,L. Suarez,Luis Suarez,FC Barcelona,https://cdn.sofifa.org/18/teams/241.png,2291,30,Spanish Primera Division,1987-01-24,182.0,...,0,0,0,2,0,0,0,0,0,Luis

In [88]:
Fixed1213.head(4)

,ID,name,full_name,club,club_logo,special,age,league,birth_date,height_cm,...,Red,Sub,CO,Off,Pen SV,Pen M,Goals conceded,Conceded 1+,OG,Firstname
0,188152,Oscar,Oscar dos Santos Emboaba,NaN,NaN,1961,25,NaN,1991-09-09,179.0,...,0,18,12,21,0,0,0,0,0,Oscar
1,239335,Oscar,Oscar Rodriguez Arnaiz,Real Madrid CF,https://cdn.sofifa.org/18/teams/243.png,1667,19,Spanish Primera Division,1998-06-28,174.0,...,0,18,12,21,0,0,0,0,0,Oscar
2,208421,Saul,Saul Niguez Esclapez,Atletico Madrid,https://cdn.sofifa.org/18/teams/240.png,2092,22,Spanish Primera Division,1994-11-21,181.0,...,0,1,0,0,0,0,0,0,0,Saul
3,219709,Saul,Saul Garcia Cabrero,RC Deportivo de La Coruna,https://cdn.sofifa.org/18/teams/242.png,1719,22,Spanish Primera Division,1994-11-09,183.0,...,0,1,0,0,0,0,0,0,0,Saul